-- Schema ringkas SQLite untuk dokumentasi proyek.
-- Sumber utama struktur database tetap migration Laravel pada database/migrations.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, email_verified_at DATETIME NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'nasabah', phone VARCHAR(30) NULL, address TEXT NULL, is_active INTEGER NOT NULL DEFAULT 1, remember_token VARCHAR(100) NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS waste_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(255) NOT NULL UNIQUE, description TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS wastes (id INTEGER PRIMARY KEY AUTOINCREMENT, waste_category_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, price_per_kg NUMERIC NOT NULL DEFAULT 0, stock_kg NUMERIC NOT NULL DEFAULT 0, image VARCHAR(255) NULL, is_active INTEGER NOT NULL DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, FOREIGN KEY(waste_category_id) REFERENCES waste_categories(id));
CREATE TABLE IF NOT EXISTS deposits (id INTEGER PRIMARY KEY AUTOINCREMENT, code VARCHAR(255) NOT NULL UNIQUE, customer_id INTEGER NOT NULL, officer_id INTEGER NULL, deposit_date DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', total_weight NUMERIC NOT NULL DEFAULT 0, total_amount NUMERIC NOT NULL DEFAULT 0, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, FOREIGN KEY(customer_id) REFERENCES users(id), FOREIGN KEY(officer_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS deposit_details (id INTEGER PRIMARY KEY AUTOINCREMENT, deposit_id INTEGER NOT NULL, waste_id INTEGER NOT NULL, weight_kg NUMERIC NOT NULL, price_per_kg NUMERIC NOT NULL, subtotal NUMERIC NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(deposit_id) REFERENCES deposits(id), FOREIGN KEY(waste_id) REFERENCES wastes(id));
CREATE TABLE IF NOT EXISTS deposit_status_histories (id INTEGER PRIMARY KEY AUTOINCREMENT, deposit_id INTEGER NOT NULL, from_status VARCHAR(255) NULL, to_status VARCHAR(255) NOT NULL, changed_by INTEGER NOT NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(deposit_id) REFERENCES deposits(id), FOREIGN KEY(changed_by) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS withdrawals (id INTEGER PRIMARY KEY AUTOINCREMENT, code VARCHAR(255) NOT NULL UNIQUE, customer_id INTEGER NOT NULL, processed_by INTEGER NULL, amount NUMERIC NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', payment_proof VARCHAR(255) NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, FOREIGN KEY(customer_id) REFERENCES users(id), FOREIGN KEY(processed_by) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS withdrawal_status_histories (id INTEGER PRIMARY KEY AUTOINCREMENT, withdrawal_id INTEGER NOT NULL, from_status VARCHAR(255) NULL, to_status VARCHAR(255) NOT NULL, changed_by INTEGER NOT NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(withdrawal_id) REFERENCES withdrawals(id), FOREIGN KEY(changed_by) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS account_ledgers (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, type VARCHAR(20) NOT NULL, reference_type VARCHAR(50) NOT NULL, reference_id INTEGER NOT NULL, amount NUMERIC NOT NULL, description VARCHAR(255) NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(customer_id) REFERENCES users(id), UNIQUE(reference_type, reference_id));
CREATE TABLE IF NOT EXISTS app_notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, link VARCHAR(255) NULL, read_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS complaints (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, attachment VARCHAR(255) NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', response TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, FOREIGN KEY(customer_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS complaint_status_histories (id INTEGER PRIMARY KEY AUTOINCREMENT, complaint_id INTEGER NOT NULL, from_status VARCHAR(255) NULL, to_status VARCHAR(255) NOT NULL, changed_by INTEGER NOT NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, FOREIGN KEY(complaint_id) REFERENCES complaints(id), FOREIGN KEY(changed_by) REFERENCES users(id));
